### PR TITLE
Forecast fix for Home Assistant >= 2024.4.0

### LINKED ISSUE #149: Broken on HA 2024.4.0b0
**Environment**
- Home Assistant Core release with the issue: 2024.4.0b0
- This custom component release with the issue: 1.4.6
- Last working this custom component release (if known): n/a
- Operating environment (Home Assistant/Supervisor/Docker/venv): HA OS

**Describe the bug**
After updating HA to 2023.4 the integration does not load anymore.

**Steps to Reproduce**
Update to HA core April beta release.

**Expected behavior**
Integration still works.

**Debug log**
```text
Logger: homeassistant.config
Source: config.py:1437
First occurred: 20:50:40 (1 occurrences)
Last logged: 20:50:40

Platform error: binary_sensor - cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1437, in _async_load_and_validate_platform_integration
    platform = await p_integration.integration.async_get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1072, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1147, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1135, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1062, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1235, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1265, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/snowtire/binary_sensor.py", line 19, in <module>
    from homeassistant.components.weather import (
ImportError: cannot import name 'ATTR_FORECAST' from 'homeassistant.components.weather' (/usr/src/homeassistant/homeassistant/components/weather/__init__.py)
```

### PR DESCRIPTION
**Pull request by fcastilloec**
## Proposed change

Fix support for new service request for forecast

## Type of change

- [x] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an this integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example entry for `configuration.yaml`:

```yaml
# Example configuration.yaml

```

## Additional information

- This PR fixes or closes issue: fixes #149 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Black (`black --fast custom_components`)

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated to README.md

### CODE REVIEW

**Comment by fcastilloec** [comment]
I tried my best for tests to pass, both `pre-commit` and CI tests but I had trouble with `mypy` and `pylint` local tests.
Also, testing the integration itself was challenging since implementing a mock weather integration is something I'm not familiar with. I've tested with various weather providers that implement the new `get_forecasts` service request and it's working without issues.

**Comment by phedoreanu** [comment]
@Limych any chance for a review? 😃

**Review by denysdovhan — APPROVED** [review]
Please, merge this PR

**Comment by Limych** [comment]
Please, fix errors in requirements and add unit tests for your code.

**Comment by fcastilloec** [comment]
@Limych Thanks for taking a look at this PR. As I mentioned earlier, I can't fix all the tests needed for this PR.
I've fixed the lint testing but I can't fix "Test Package" because I don't know how to create a mock weather integration for testing.
For the moment, I included `@pytest.mark.skip(reason="Can't mock a weather integration")` on the `test_async_update` so I can make sure that the other test, which I know how they work, can run and pass.

I hope you can take this PR and make the modifications yourself so the main test can pass. If somebody else knows how to mock a service call to a weather integration, and can help me with it, I'd appreciate it. At the moment, this is as far as I can go.

For anybody else following this PR and needs a fix immediately, check the two following files in this PR (or my fork), and copy/paste them under your setup:
`custom_components/snowtire/binary_sensor.py`
`custom_components/snowtire/manifest.json`
All the other files changed in this PR are only for the tests, pre-commit, dev-container, etc; and aren't needed for the actual integration.

**Comment by Limych** [comment]
Ok, thanks for your work.

Unfortunately, I cannot accept PR without full-fledged unit tests, because then no one will do them and this will entail a deterioration in the quality of the code of the entire component.
And right now, unfortunately, I don’t have the opportunity to work on this component yet.

**Comment by fcastilloec** [comment]
@Limych after some googling and reading, I found out how to mock a service call. The unit test has been fixed to implement it, and the tests should be passing. Can you approve it so the workflow runs? If there are any additional errors after that, I could fix them.

**Comment by phedoreanu** [comment]
@Limych please merge it until the end of October 😅

Edit: Also please approve the workflow

**Comment by Limych** [comment]
Thanks :heart:
